version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint..."
      - pip install cfn-lint

  pre_build:
    commands:
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity || echo "Missing permissions or IAM role not attached."

  build:
    commands:
      - echo "Validating template..."
      - cfn-lint template.yaml
      - echo "Deploying stack..."
      - aws cloudformation deploy --stack-name IreneVanessaStack --template-file template.yaml --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --debug

artifacts:
  files:
    - '**/*'
