version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint and AWS CLI..."
      - pip install cfn-lint

  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint template.yaml
      - echo "Validation passed. Deploying CloudFormation stack..."
      - echo "Enabling debug output..."
      - export AWS_DEFAULT_REGION=us-east-1
      - aws cloudformation deploy \
          --stack-name IreneVanessaStack \
          --template-file template.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --debug

artifacts:
  files:
    - '**/*'
  name: ValidatedAndDeployedTemplate
