version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint and AWS CLI..."
      - pip install cfn-lint
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install || ./aws/install

  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint template.yaml
      - echo "CloudFormation template validation passed!"
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --stack-name IreneVanessaStack \
          --template-file template.yaml \
          --capabilities CAPABILITY_NAMED_IAM
      - echo "Build and deployment completed successfully!"

artifacts:
  files:
    - '**/*'
  name: ValidatedAndDeployedTemplate
