version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint..."
      - pip install cfn-lint

  build:
    commands:
      - echo "Validating CloudFormation template..."
      - cfn-lint template.yaml
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --stack-name IreneVanessaStack \
          --template-file template.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1
      - echo "✅ Stack deployment successful!"

artifacts:
  files:
    - '**/*'
  name: ValidatedTemplate
